version: "3.9"
# This section defines all of our components as "services", each which is
# itself a docker image [1].
services:
  # This section defines our PostgreSQL database [2].
  # Note that the name `db` also becomes the hostname of the postgres container
  ansible:
    build:
      dockerfile: ansible/dockerfile